version: '3.9'
services:
  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "notifier"
    restart: always
    env_file:
      - .env
    volumes:
      - /home/sasha/Pictures/akibot:/app/content:rw
      - ./log:/app/log:rw
#      - /opt/akibot/content:/app/content:rw
#      - /opt/akibot/log:/app/log:rw

