version: '3.9'
services:
  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aki-bot"
    restart: always
    env_file:
      - .env
    volumes:
      - /opt/akibot/content:/app/content:rw
      - /var/log/akibot:/app/log:rw