name: Zaubumba Siyay ans Sidi

on:
  push:
    branches:
      - master
    # paths:
    #   - 'bot/**'

jobs:
  gitguardian_scan:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.26.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  build_aki_bot_core:
    name: Build Aki-Bot
    runs-on: ubuntu-latest
    needs: gitguardian_scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Docker registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_URL }}
      
      - name: Build and tag Aki-Bot Docker image
        run: |
          cd ./bot
          docker build . --file Dockerfile --tag aki-bot-core:stable
          docker tag aki-bot-core:stable ${{ secrets.REGISTRY_URL }}/aki-bot-core:stable

      - name: Push Docker image to registry
        run: docker push ${{ secrets.REGISTRY_URL }}/aki-bot-core:stable

  deploy_aki_bot_core:
    name: Deploy Aki-Bot Image
    runs-on: ubuntu-latest
    needs: build_aki_bot_core
    steps:
      - name: SSH to Server and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            /opt/aki-bot/aki-bot-core-deploy.sh
