name: Aki-Bot Builder

on:
  push:
    branches:
      - master

jobs:
  gitguardian_scan:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.26.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  check_files:
    name: Check files
    runs-on: ubuntu-latest
    needs: [gitguardian_scan]
    outputs:
      RUN_JOB_BOT: ${{ steps.check_files.outputs.run_job_bot }}
      RUN_JOB_IMAGE: ${{ steps.check_files.outputs.run_job_image }}
      RUN_JOB_VIDEO: ${{ steps.check_files.outputs.run_job_video }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD > files.txt

          while IFS= read -r file; do
            echo $file
            if [[ $file == bot/* ]]; then
              echo "This modified file is under the 'bot' folder."
              echo "run_job_bot=true" >> "$GITHUB_OUTPUT"
            elif [[ $file == image/* ]]; then
              echo "This modified file is under the 'image' folder."
              echo "run_job_image=true" >> "$GITHUB_OUTPUT"
            elif [[ $file == video/* ]]; then
              echo "This modified file is under the 'video' folder."
              echo "run_job_video=true" >> "$GITHUB_OUTPUT"
            fi
          done < files.txt

  build_aki_bot_core:
    name: Build Aki-Bot-Core
    runs-on: ubuntu-latest
    needs: [check_files]
    if: ${{ needs.check_files.outputs.RUN_JOB_BOT == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to Docker registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_URL }}
      - name: Build and tag Docker image
        run: |
          docker build . --file bot/Dockerfile --tag aki-bot-core:stable
          docker tag aki-bot-core:stable ${{ secrets.REGISTRY_URL }}/aki-bot-core:stable
      - name: Push Docker image to registry
        run: docker push ${{ secrets.REGISTRY_URL }}/aki-bot-core:stable

  deploy_aki_bot_core:
    name: Deploy Aki-Bot-Core
    runs-on: ubuntu-latest
    needs: [build_aki_bot_core]
    steps:
      - name: SSH to Server and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            /bin/bash /opt/aki-bot/core/aki-bot-core-deploy.sh

  build_aki_bot_image:
    name: Build Aki-Bot Images
    runs-on: ubuntu-latest
    needs: [check_files]
    if: ${{ needs.check_files.outputs.RUN_JOB_IMAGE == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to Docker registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_URL }}
      - name: Build and tag Docker image
        run: |
          docker build . --file bot/Dockerfile --tag aki-bot-image:stable
          docker tag aki-bot-image:stable ${{ secrets.REGISTRY_URL }}/aki-bot-image:stable
      - name: Push Docker image to registry
        run: docker push ${{ secrets.REGISTRY_URL }}/aki-bot-image:stable

  deploy_aki_bot_image:
    name: Deploy Aki-Bot-Image
    runs-on: ubuntu-latest
    needs: [build_aki_bot_image]
    steps:
      - name: SSH to Server and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            /bin/bash /opt/aki-bot/image/aki-bot-image-deploy.sh

  build_aki_bot_video:
    name: Build Aki-Bot Video
    runs-on: ubuntu-latest
    needs: [check_files]
    if: ${{ needs.check_files.outputs.RUN_JOB_VIDEO == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to Docker registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY_URL }}
      - name: Build and tag Docker image
        run: |
          docker build . --file bot/Dockerfile --tag aki-bot-video:stable
          docker tag aki-bot-video:stable ${{ secrets.REGISTRY_URL }}/aki-bot-video:stable
      - name: Push Docker image to registry
        run: docker push ${{ secrets.REGISTRY_URL }}/aki-bot-video:stable

  deploy_aki_bot_video:
    name: Deploy Aki-Bot-Image
    runs-on: ubuntu-latest
    needs: [build_aki_bot_video]
    steps:
      - name: SSH to Server and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            /bin/bash /opt/aki-bot/video/aki-bot-video-deploy.sh
