name: Aki-Bot Builder

on:
  push:
    branches:
      - master

jobs:
  gitguardian_scan:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.26.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  build_aki_bot_core:
    name: Build Aki-Bot-Core
    runs-on: ubuntu-latest
    needs: gitguardian_scan
    if: github.event_name == 'push' && github.event.head_commit.modified | contains('bot/')
    steps:
      - name: Use Docker Build & Push template
        uses: ./.github/actions/docker_build_push
        with:
          image_name: aki-bot-core
          image_tag: stable

  deploy_aki_bot_core:
    name: Deploy Aki-Bot-Core
    runs-on: ubuntu-latest
    needs: build_aki_bot_core
    if: always()
    steps:
      - name: SSH to Server and Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            /bin/bash /opt/aki-bot/core/aki-bot-core-deploy.sh

  build_aki_bot_images:
    name: Build Aki-Bot Images
    runs-on: ubuntu-latest
    needs: gitguardian_scan
    if: github.event_name == 'push' && github.event.head_commit.modified | contains('image-prep/')
    steps:
      - name: Use Docker Build & Push template
        uses: ./.github/actions/docker_build_push
        with:
          image_name: aki-bot-images
          image_tag: stable
